version: 0.2

phases:
  build:
    commands:
      - mvn clean install -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/jackson-lombok-1.1.jar
